### ISSUE TITLE
Node 6.0.0 error: "Module version mismatch. Expected 48, got 47"

### ISSUE THREAD

**Issue by TehShrike** [nolanlawson/local-npm#119]
I don't have any particular clue here.

```sh
$  local-npm
/Users/josh/npm/lib/node_modules/local-npm/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/josh/npm/lib/node_modules/local-npm/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

**Comment by nolanlawson** [comment]
This seems to be an issue with leveldown. Typically these problems can only be resolved by uninstalling `local-npm` and then reinstalling it. (Especially after you upgrade node/npm.)

Let me know if that helps!

**Comment by TehShrike** [comment]
I tried uninstalling and reinstalling.  I got some warnings on install:
```
$  npm i local-npm -g
/Users/josh/npm/bin/local-npm -> /Users/josh/npm/lib/node_modules/local-npm/lib/bin.js

> sqlite3@3.1.3 install /Users/josh/npm/lib/node_modules/local-npm/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:9704:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:143:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:227:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:505:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:605:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings generated.
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc:118:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/statement.cc:322:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Bind);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:370:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Get);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:438:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Run);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:504:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(All);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:601:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Each);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:724:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Reset);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
7 warnings generated.
  SOLINK_MODULE(target) Release/node_sqlite3.node
  COPY /Users/josh/npm/lib/node_modules/local-npm/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp

> leveldown@1.4.5 install /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown
> prebuild --install
...etc
```

And then these errors when I tried to launch:

```
$  local-npm
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0xfc84f5c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0xc7240a82724] (this=0x21b5b23f47f9 <an Object with map 0x79079d17be1>#1#,module=0x105219621 <a Module with map 0x79079d181b9>#2#,filename=0x1052195f9 <String[94]: /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown/build/Release/leveldown.node>)
    2: load [module.js:456] [pc=0xc7240938e72] (this=0x105219621 <a Module with map 0x79079d181b9>#2#,filename=0x1052195f9 <String[94]: /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown/build/Release/leveldown.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0xc724093899d] (this=0xfc84f504189 <undefined>,module=0x105219621 <a Module with map 0x79079d181b9>#2#,filename=0x1052195f9 <String[94]: /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown/build/Release/leveldown.node>)
    4: _load [module.js:407] [pc=0xc72409345e2] (this=0x21b5b23f47b1 <JS Function Module (SharedFunctionInfo 0x21b5b23286a1)>#3#,request=0x105218681 <String[94]: /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown/build/Release/leveldown.node>,parent=0x10520b1d1 <a Module with map 0x79079d181b9>#4#,isMain=0xfc84f504299 <false>)
[pc=0xc7240a7daee] (this=0x1051e2a79 <an Object with map 0x31d078207bc9>#6#,exports=0x1051e2a79 <an Object with map 0x31d078207bc9>#6#,require=0x1051e5219 <JS Function require (SharedFunctionInfo 0x21b5b2358ec9)>#7#,module=0x1051e2a29 <a Module with map 0x79079d181b9>#8#,__filename=0x1051e2a01 <String[78]: /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown/leveldown.js>,__dirname=0x1051e51b1 <String[65]: /Users/josh/npm/lib/node_modules/local-npm/node_modules/leveldown>)
,path=0x2556a83bbde9 <String[9]: leveldown>)
79d181b9>#13#,path=0x21b5b235dbf9 <String[5]: level>)
this=0x21b5b23f4879 <a Module with map 0x79079d181b9>#17#,path=0x21b5b2358371 <String[7]: ./index>)
575] [pc=0xc72409340aa] (this=0x21b5b23f47b1 <JS Function Module (SharedFunctionInfo 0x21b5b23286a1)>#3#)

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: leveldown::Database::Init()
 3: leveldown::Init(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0xc724080961b
 9: 0xc7240a82724
Segmentation fault: 11
```

node 6.0.0, npm 3.8.6.

**Comment by nolanlawson** [comment]
Those look like node/npm errors. I do know that PouchDB currently does not support Node 6, so that's probably what you're running into. You may need to completely reinstall from scratch and `npm cache clean` as well.

**Comment by lidakis** [comment]
TehShrike I have a working solution for you.
I had exact the same problem as you and I found out the following.

If you use pouchdb in node like this   var PouchDB = require('pouchdb'); the npm package is not updated to the latest version of pouch db code.

solution: 
1) Go to node_modules/pouchdb/lib/index.js
2) Open that file.
3) Then go [here ](https://cdn.jsdelivr.net/pouchdb/5.4.4/pouchdb.js) and copy the whole code and paste it in index.js file (node_modules/pouchdb/lib/index.js).
4) save the file (index.js).
5) Run your app.

This worked for me with node6 as well as in node webkit 0.15.4 with any version of npm that you referred and also with the latest.

Hope this helps.

Best Regards.

**Comment by TehShrike** [comment]
hmm, if PouchDB is reinstalled entirely, it should download PouchDB 5.4.4 https://github.com/nolanlawson/local-npm/blob/master/package.json#L36

**Comment by lidakis** [comment]
Of course, I had exact the same issue and for some reason, the code in this file was different that the latest version of pouchdb, even if I had the version 5.0.0 in package.json referred.
And note that was after a whole new build of npm, node, e.t.c.
Sometimes shit happens, with all different and compatible versions between all those things ;)

And make sure that there is any other import of pouchdb in any other place in your app. For instance if you have .html files make sure that do not import pouchdb in script tag in htlm files.

Let me know if this worked.

**Comment by jtlindsey** [comment]
@lidakis I just did a `npm install --save pouchdb` on a new electron project and had the same issue. Then I used your solution but grabbed the current version of pouchdb that [mached](https://cdnjs.cloudflare.com/ajax/libs/pouchdb/5.4.5/pouchdb.js) my package.json `"pouchdb": "^5.4.5"` and it worked. 

Im on Linux using
```
npm -v
3.10.3
node --version
v6.3.0
```
