### ISSUE TITLE
Configuration issues?

### ISSUE THREAD

**Issue by drpicox** [nolanlawson/local-npm#40]
```bash
$ local-npm

Welcome!
To start using local-npm, just run: 

  $ npm set registry http://127.0.0.1:5080

To switch back, you can run: 

  $ npm set registry https://registry.npmjs.org

A simple npm-like UI is available here: http://127.0.0.1:5080/_browse

PouchDB Server listening on port 16984.
Navigate to http://localhost:16984/_utils for the Fauxton UI.

error doing logger.info() on https://skimdb.npmjs.com/registry
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
error doing logger.info() on https://skimdb.npmjs.com/registry
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
error doing logger.info() on https://skimdb.npmjs.com/registry
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
error doing logger.info() on https://skimdb.npmjs.com/registry
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
...
error doing logger.info() on https://skimdb.npmjs.com/registry
{"status":503,"name":"pound_service_unavailable","message":"Database encountered an unknown error"}
GET /lodash 200 573.090 ms - -
error doing logger.info() on https://skimdb.npmjs.com/registry
{"status":503,"name":"pound_service_unavailable","message":"Database encountered an unknown error"}
...
```
go offline and reinstalling lodash
```bash
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
error doing logger.info() on https://skimdb.npmjs.com/registry
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
error doing logger.info() on https://skimdb.npmjs.com/registry
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND registry.npmjs.org
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
$
```

I guess that it is not intended to work offline neither with intermitent network connection, right?

**Comment by nolanlawson** [comment]
Yup, it's designed to replicate from a live npmjs.com somewhere. You can make it work offline by running it on a machine that's connected to the internet, replicating, then copying all those files to a new machine and re-running it there. Unfortunately that will mean that it will never be updated, though.

**Comment by nolanlawson** [comment]
As for intermittent network connections, I'm working on a fix for that. It should work.

**Comment by nolanlawson** [comment]
Should be fixed by https://github.com/nolanlawson/local-npm/pull/41, please reopen if it's not.
