### ISSUE TITLE
Error "Could not locate the bindings file"

### ISSUE THREAD

**Issue by DavidBrower** [nolanlawson/local-npm#90]
**node-gyp v3.2.1**
**node.js v5.3.0**
**npm v3.5.3**
**prebuild v2.8.1**

When I run local-npm I get the following error: 

C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules\bi
ndings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\build\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\build\Debug\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\build\Release\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\out\Debug\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\Debug\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\out\Release\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\Release\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\build\default\leveldown.node
 → C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-npm\node_modules
\leveldown\compiled\5.3.0\win32\x64\leveldown.node
    at bindings (C:\Users\david.brower\AppData\Roaming\npm\node_modules\local-np
m\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\david.brower\AppData\Roaming\npm\node_module
s\local-npm\node_modules\leveldown\leveldown.js:4:46)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\david.brower\AppData\Roaming\npm\node_module
s\local-npm\node_modules\level\level.js:1:106)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\david.brower\AppData\Roaming\npm\node_module
s\local-npm\lib\index.js:10:13)

**Comment by nolanlawson** [comment]
This seems like an error with [leveldown](https://github.com/Level/leveldown); I know that history there have been issues with Windows machines. You might try searching over there to see if your version of Windows has known issues.

**Comment by DavidBrower** [comment]
Thanks, Nolan.

**Comment by smmoosavi** [comment]
I have same error in linux
```
/home/myuser/npm-global/lib/node_modules/local-npm/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/build/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/build/Debug/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/build/Release/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/out/Debug/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/Debug/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/out/Release/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/Release/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/build/default/leveldown.node
 → /home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/compiled/5.3.0/linux/x64/leveldown.node
    at bindings (/home/myuser/npm-global/lib/node_modules/local-npm/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/myuser/npm-global/lib/node_modules/local-npm/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/myuser/npm-global/lib/node_modules/local-npm/node_modules/level/level.js:1:106)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/myuser/npm-global/lib/node_modules/local-npm/lib/index.js:10:13)

```

**Comment by nolanlawson** [comment]
It's a `leveldown-prebuilt` issue, probably related to the architecture you're running on. Try clearing out the npm cache and installing again. Sorry about that!

**Comment by webline** [comment]
Some problem here on a Mac:

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/build/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/Debug/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/out/Release/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/Release/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/build/default/leveldown.node
 → /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/compiled/9.4.0/darwin/x64/leveldown.node
    at bindings (/usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/level/level.js:1:106)

I cleared the cache and did a rebuild - no change so far
